### ISSUE TITLE
Creating entry quits program

### ISSUE THREAD

**Issue by nguyen-anthony** [bashbunni/pjs#20]
When attempting to create an entry using the `c` key, it quits the program. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/53980868/171490627-9f611367-66e1-4458-8dc6-d7854eeaccce.png)

**Comment by bashbunni** [comment]
Hey! Sorry I broke it with the latest update of Bubble Tea as the API changed since I previously implemented it. It should work now

**Comment by nguyen-anthony** [comment]
Works perfectly now. Cool cool.
