### ISSUE TITLE
Crash while deleting zero projects

### ISSUE THREAD

**Issue by Naegolus** [bashbunni/pjs#23]
Hi,

how to reproduce.

1. Starting app
$ ./project-management
what would you like to name your project?
First

2. Starting app again
List of projects is shown

3. Press "d" two times

Result:
$ ./project-management
Caught panic:
runtime error: index out of range [0] with length 0
Restoring terminal...

Expected:
No change or message

**Comment by BrianMwangi21** [comment]
@bashbunni I would like to fix this issue and I have a branch ready but no rights to push the branch and create a PR. 

Please assist
